from time import sleep
import os

print("Izaberite jedno:")
print("A.   Izvori Zagadjenja    || B. Zagadjivaci                 ||  C.   Posledice")
print("-------------------------------------------------------------------------------------------------------------------------------")
print("A1.  Voznja automobilom   || B1.  Ugljen Dioksid CO2        ||  C1.  Efekat staklene baste")
print("A2.  Sagorevanje uglja    || B2.  Ugljen monoksid           ||  C2.  Fotohemijski smog")
print("A3.  Sagorevanje drveta   || B3.  Razni ugljovodonici       ||  C3.  Kancerogeneza, mutageneza, teragogeneza")
print("A4.  Emisija metana       || B4.  Polikondenzovani          ||  C4.  Poremecaj normalnih hemijskih procesa")
print("                          ||      aromaticni ugljovodonici  ||       u vazduhu")
print("A5.  Paljenje vatre u     || B5.  Oksidi azota              ||  C5.  Kisele kise")
print("     kontejneru za smece  ||                                ||")
print("A6.  Pusenje cigareta     || B6.  Jedinjenja olova          ||  C6.  Trovanje zivog sveta")
print("A7.  Prerada sulfidnih    || B7.  Aerosol                   ||  C7.  Ulazenje zagadjivaca u lanac ishrane")
print("     ruda                 ||                                ||")
print("A8.  Emisija freona       || B8.  Tetrahlorodibenzodioksini ||  C8.  Hemijski slog")
print("A9.  Nestrucna primena    || B9.  Oksidi sumpora            ||  C9.  Razaranje ozonskog sloja")
print("     pesticida            ||                                ||")
print("A10. Sipanje ulja za     || B10.  Fenoli                    ||  C10. Eutrofikacija povrsinskih voda")
print("     podmazivanje         ||                                ||")
print("     u kanalizaciju       ||                                ||")
print("A11. Dezinfekcija pijace  || B11. Jedinjenja kadmijuma      ||  C11. Poremecaj normalnih hemijskih procesa")
print("     vode hlorom          ||                                ||       u vodi")
print("A12. Unosenje fenola      || B12. Metan                     ||  C12. Zagadjivanje voda, podzemih voda i zemljista")
print("     u vode               ||                                ||")
print("A13. Unosenje fosfata u   || B13. Freoni                    ||  C13. Posledice - Trovanje zivog sveta, zagadjivanje zemljista,")
print("     povrsinske vode      ||                                ||       podzemnih i povrsinskih voda i zagadjivanje vazduha")
print("A14. Unosenje soli teskih || B14. Trihalometani             ||")
print("     metala u vode ili    ||                                ||")
print("     u zemljiste          ||                                ||")
print("A15. Unosenje elementarne || B15. Razni Pesticidi           ||")
print("     (metalne) zive u     || B16. Fosfati                   ||")
print("     zemljiste ili vode   || B17. Joni teskih metala        ||")
print("                          || B18. Jedinjenja zive           ||")
print("                          || B19. Metil - Ziva              ||")


zlo = input("Unesite zeljeno zlo\n")
if(zlo == "A1"):
	os.system("clear") 
	os.system("cls") 
	print("A.   Izvori Zagadjenja    || B. Zagadjivaci                 ||  C.   Posledice")
	print("-------------------------------------------------------------------------------------------------------------------------------")
	print("A1.  (Voznja automobilom) || B1.  Ugljen Dioksid CO2        ||  C1.  Efekat staklene baste")
	print("A2.  -----------------    || B2.  Ugljen monoksid           ||  C2.  Fotohemijski smog")
	print("A3.  Sagorevanje drveta   || B3.  Razni ugljovodonici       ||  C3.  Kancerogeneza, mutageneza, teragogeneza")
	print("A4.  Emisija metana       || B4.  Polikondenzovani          ||  C4.  Poremecaj normalnih hemijskih procesa")
	print("                          ||      aromaticni ugljovodonici  ||       u vazduhu")
	print("A5.  -----------------    || B5.  Oksidi azota              ||  C5.  Kisele kise")
	print("     -----------------    ||                                ||")
	print("A6.  Pusenje cigareta     || B6.  Jedinjenja olova          ||  C6.  Trovanje zivog sveta")
	print("A7.  Prerada sulfidnih    || B7.  Aerosol                   ||  C7.  Ulazenje zagadjivaca u lanac ishrane")
	print("     ruda                 ||                                ||")
	print("A8.  Emisija freona       || B8.  Tetrahlorodibenzodioksini ||  C8.  Hemijski slog")
	print("A9.  Nestrucna primena    || B9.  Oksidi sumpora            ||  C9.  Razaranje ozonskog sloja")
	print("     pesticida            ||                                ||")
	print("A10. Sipanje ulja za     || B10.  Fenoli                    ||  C10. Eutrofikacija povrsinskih voda")
	print("     podmazivanje         ||                                ||")
	print("     u kanalizaciju       ||                                ||")
	print("A11. Dezinfekcija pijace  || B11. Jedinjenja kadmijuma      ||  C11. Poremecaj normalnih hemijskih procesa")
	print("     vode hlorom          ||                                ||       u vodi")
	print("A12. Unosenje fenola      || B12. Metan                     ||  C12. Zagadjivanje voda, podzemih voda i zemljista")
	print("     u vode               ||                                ||")
	print("A13. Unosenje fosfata u   || B13. Freoni                    ||  C13. Posledice - Trovanje zivog sveta, zagadjivanje zemljista,")
	print("     povrsinske vode      ||                                ||       podzemnih i povrsinskih voda i zagadjivanje vazduha")
	print("A14. Unosenje soli teskih || B14. Trihalometani             ||")
	print("     metala u vode ili    ||                                ||")
	print("     u zemljiste          ||                                ||")
	print("A15. Unosenje elementarne || B15. Razni Pesticidi           ||")
	print("     (metalne) zive u     || B16. Fosfati                   ||")
	print("     zemljiste ili vode   || B17. Joni teskih metala        ||")
	print("                          || B18. Jedinjenja zive           ||")
	print("                          || B19. Metil - Ziva              ||")